//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert_2", ReplyAction="http://tempuri.org/IService1/Convert_2Response")]
        string Convert_2(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert_2", ReplyAction="http://tempuri.org/IService1/Convert_2Response")]
        System.Threading.Tasks.Task<string> Convert_2Async(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert_8", ReplyAction="http://tempuri.org/IService1/Convert_8Response")]
        string Convert_8(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert_8", ReplyAction="http://tempuri.org/IService1/Convert_8Response")]
        System.Threading.Tasks.Task<string> Convert_8Async(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert_16", ReplyAction="http://tempuri.org/IService1/Convert_16Response")]
        string Convert_16(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert_16", ReplyAction="http://tempuri.org/IService1/Convert_16Response")]
        System.Threading.Tasks.Task<string> Convert_16Async(int i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Convert_2(int i) {
            return base.Channel.Convert_2(i);
        }
        
        public System.Threading.Tasks.Task<string> Convert_2Async(int i) {
            return base.Channel.Convert_2Async(i);
        }
        
        public string Convert_8(int i) {
            return base.Channel.Convert_8(i);
        }
        
        public System.Threading.Tasks.Task<string> Convert_8Async(int i) {
            return base.Channel.Convert_8Async(i);
        }
        
        public string Convert_16(int i) {
            return base.Channel.Convert_16(i);
        }
        
        public System.Threading.Tasks.Task<string> Convert_16Async(int i) {
            return base.Channel.Convert_16Async(i);
        }
    }
}
